import { InputType } from '../../../common/enums/input-type.enum';
import { Language } from '../../../common/enums/language.enum';
import { NodeType } from '../../../common/enums/node-type.enum';

export const menstruationSeed = {
  category: {
    code: 'MENSTRUATION',
    titleEn: 'Menstruation',
    titleSw: 'Hedhi',
    descriptionEn: null,
    descriptionSw: null,
    introMessageEn:
      "Let's learn about menstruation, menstrual hygiene, menstrual pain, fertility, myths and common concerns.",
    introMessageSw:
      'Karibu! Tujifunze kuhusu hedhi, usafi wa hedhi, maumivu ya hedhi, uwezo wa kushika mimba, dhana potofu na wasiwasi wa kawaida.',
    introMediaAssetKey: 'image_menstruation_intro_01',
    audienceGender: null,
    ageBandRule: null,
    sortOrder: 2,
    isActive: true,
  },

  topic: {
    code: 'MENSTRUATION',
    titleEn: 'Menstruation',
    titleSw: 'Hedhi',
    descriptionEn: null,
    descriptionSw: null,
    audienceGender: null,
    ageBandRule: null,
    sortOrder: 1,
    isActive: true,
  },

  subtopics: [
    {
      code: 'WHAT_IS_MENSTRUATION',
      titleEn: 'What is a period?',
      titleSw: 'Hedhi ni nini?',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 1,
      isActive: true,
    },
    {
      code: 'MENSTRUAL_HYGIENE',
      titleEn: 'Menstrual Hygiene',
      titleSw: 'Usafi wa Hedhi',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 2,
      isActive: true,
    },
    {
      code: 'MENSTRUAL_PAIN_AND_CONCERNS',
      titleEn: 'Pain and concerns',
      titleSw: 'Maumivu',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 3,
      isActive: true,
    },
    {
      code: 'OVULATION_AND_FERTILITY',
      titleEn: 'Ovulation',
      titleSw: 'Utoaji wa yai',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 4,
      isActive: true,
    },
    {
      code: 'MENSTRUATION_MYTHS',
      titleEn: 'Myths and facts',
      titleSw: 'Dhana na ukweli',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 5,
      isActive: true,
    },
    {
      code: 'MENSTRUATION_COMMON_CONCERNS',
      titleEn: 'Common concerns',
      titleSw: 'Wasiwasi',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 6,
      isActive: true,
    },
    {
      code: 'MENSTRUATION_SUPPORT',
      titleEn: 'Get support',
      titleSw: 'Pata msaada',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 7,
      isActive: true,
    },
  ],

  contentNodes: [
    // WHAT_IS_MENSTRUATION
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation, commonly called a period, is the monthly shedding of the lining of the uterus through the vagina when pregnancy does not occur.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_what_is_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni kumwagika kila mwezi kwa utando wa uzazi kupitia uke wakati mimba haitokei.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_what_is_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is a normal biological process and an important sign that the reproductive system is developing.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni mchakato wa kawaida wa kibiolojia na ishara muhimu kwamba mfumo wa uzazi unakua.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Each month, a girl's body prepares for a possible pregnancy.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kila mwezi, mwili wa msichana hujiandaa kwa mimba inayowezekana.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `The ovaries release an egg and the lining of the uterus becomes thicker.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ovari hutoa yai na utando wa uzazi unakuwa mzito.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_05',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `If the egg is not fertilised by sperm, pregnancy does not occur.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_05',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ikiwa yai halijarutubishwa na manii, mimba haitokei.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_06',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `The body sheds the extra uterine lining and blood through the vagina. This is called menstruation.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_06',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Mwili hutoa utando wa ziada wa uzazi na damu kupitia uke. Hii inaitwa hedhi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_07',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is a natural part of puberty and reproductive health.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_natural_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_07',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni sehemu ya asili ya kubalehe na afya ya uzazi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_natural_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_08',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is not a disease, illness, curse or punishment.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_08',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi si ugonjwa, laana wala adhabu.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Every girl experiences menstruation differently. Differences in cycle length, flow and symptoms are common.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kila msichana hupata hedhi kwa namna tofauti. Tofauti katika urefu wa mzunguko, mtiririko na dalili ni za kawaida.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.EN,
      messageText: `Frequently Asked Questions 
Q: How long does a period usually last? 
A: Most periods last between 2 and 7 days. 

Q: Is it normal to have irregular periods? 
A: Yes. Irregular cycles are common during adolescence. 

Q: Can I play sports during my period? 
A: Yes. Physical activity is generally safe during menstruation. 

Q: Can stress affect my period? 
A: Yes. Stress may affect menstrual cycles. 

Q: Is it normal to have cramps? 
A: Mild cramps are common. Severe pain should be discussed with a healthcare provider.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 10,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.SW,
      messageText: `Maswali Yanayoulizwa Mara kwa Mara 
Swali: Hedhi hudumu kwa muda gani? 
Jibu: Kwa kawaida hedhi hudumu kati ya siku 2 hadi 7. 

Swali: Je, hedhi isiyo ya kawaida ni jambo la kawaida? 
Jibu: Ndiyo. Hasa katika miaka ya mwanzo baada ya hedhi kuanza. 

Swali: Je, maumivu wakati wa hedhi ni kawaida? 
Jibu: Maumivu madogo ni kawaida, lakini maumivu makali yanahitaji ushauri wa mtoa huduma ya afya`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 10,
      isActive: true,
    },

    // MENSTRUAL_HYGIENE
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstrual hygiene refers to the practices that help girls and women manage their menstruation safely, comfortably, and with dignity.     
Good menstrual hygiene is important for health, confidence, and daily wellbeing. 
During menstruation, it is important to use clean menstrual products such as sanitary pads, tampons, menstrual cups, or clean reusable cloths that are properly washed and dried before reuse.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Usafi wa hedhi unamaanisha desturi zinazowasaidia wasichana na wanawake kusimamia hedhi yao kwa usalama, raha, na kwa heshima. 
Usafi mzuri wa hedhi ni muhimu kwa afya, kujiamini, na ustawi wa kila siku. 
Wakati wa hedhi, ni muhimu kutumia bidhaa safi za hedhi kama vile pedi za usafi, tamponi, vikombe vya hedhi, au vitambaa safi vinavyoweza kutumika tena ambavyo vimeoshwa na kukaushwa ipasavyo kabla ya kutumika tena.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },

    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.EN,
      messageText: `Menstrual products should be changed regularly, usually every 4–8 hours depending on the flow, to prevent discomfort, bad odor, skin irritation, and infections. 
It is also important to wash the genital area daily with clean water and mild soap if available. 
The vagina naturally cleans itself, so there is no need to use harsh chemicals, perfumes, or vaginal cleansing products.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.SW,
      messageText: `Bidhaa za hedhi zinapaswa kubadilishwa mara kwa mara, kwa kawaida kila baada ya saa 4-8 kulingana na mtiririko, ili kuzuia usumbufu, harufu mbaya, muwasho wa ngozi, na maambukizi. 
Pia ni muhimu kuosha sehemu za siri kila siku kwa maji safi na sabuni laini ikiwa inapatikana. 
Uke hujisafisha yenyewe kiasili, kwa hivyo hakuna haja ya kutumia kemikali kali, manukato, au bidhaa za kusafisha uke.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },

    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.EN,
      messageText: `Girls should wash their hands before and after changing menstrual products to reduce the risk of infections. 
Used disposable pads should be wrapped and disposed of properly in a bin and should not be flushed down toilets. 
Reusable materials should be washed thoroughly with clean water and soap and dried in direct sunlight whenever possible.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.SW,
      messageText: `Wasichana wanapaswa kunawa mikono yao kabla na baada ya kubadilisha bidhaa za hedhi ili kupunguza hatari ya maambukizi. 
Pedi zilizotumika zinapaswa kufungwa na kutupwa ipasavyo kwenye pipa la taka na hazipaswi kusafishwa vyooni. 
Vifaa vinavyoweza kutumika tena vinapaswa kuoshwa vizuri kwa maji safi na sabuni na kukaushwa kwenye jua moja kwa moja inapowezekana.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.EN,
      messageText: `Many girls continue attending school, playing sports, and participating in normal activities during menstruation. 
Eating a balanced diet, drinking enough water, and getting adequate rest can also help manage menstrual discomfort. 
Menstruation is a normal and healthy part of growing up, and maintaining good menstrual hygiene helps girls stay healthy, comfortable, and confident throughout their menstrual cycle.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.SW,
      messageText: `Wasichana wengi wanaendelea kuhudhuria shule, kucheza michezo, na kushiriki katika shughuli za kawaida wakati wa hedhi. 
Kula lishe bora, kunywa maji ya kutosha, na kupata mapumziko ya kutosha pia kunaweza kusaidia kudhibiti usumbufu wa hedhi. 
Hedhi ni sehemu ya kawaida na yenye afya njema ya kukua, na kudumisha usafi mzuri wa hedhi huwasaidia wasichana kubaki na afya njema, starehe, na kujiamini katika mzunguko wao wote wa hedhi.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    // MENSTRUAL_PAIN_AND_CONCERNS
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `These feelings are normal, especially during the first few years of menstruation. 
Many girls experience mild abdominal pain, back pain, breast tenderness, bleeding changes, fatigue, headaches and swelling. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hisia hizi ni za kawaida, hasa wakati wa miaka ya kwanza ya hedhi. 
Wasichana wengi hupata maumivu ya tumbo kidogo, maumivu ya mgongo, uchungu wa matiti, mabadiliko ya damu, uchovu, maumivu ya kichwa na uvimbe. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },

    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `These symptoms are often normal and vary from person to person. Some girls may feel embarrassed, scared, confused, angry and emotional. 
Some girls experience abdominal pain due to the uterine contractions, which occur when the uterus pushes menstrual blood out.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Dalili hizi mara nyingi ni za kawaida na hutofautiana kutoka kwa mtu hadi mtu. 

Baadhi ya wasichana wanaweza kuhisi aibu, woga, kuchanganyikiwa, kukasirika na kihisia. 
Baadhi ya wasichana hupata maumivu ya tumbo kutokana na mkakamao wa msukumo wa mji wa mimba, mkakamao huo hutokea wakati mji wa mimba unaposukuma damu ya hedhi itoke. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Below are some tips for things you can do to cope with the pain:
    ● Take a plastic bottle filled with warm water or a cloth soaked in warm water and place it under your back or lower abdomen.
    ● Drink water: It is good to make sure that your body is well hydrated as this will prevent headaches.
    ● Doing light exercise can help reduce pain and bloating
    gas.
    ● Painkillers such as paracetamol can help if you are feeling severe pain, but remember to use them according to the instructions of a
    health professional.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hapa chini ni vidokezo vya mambo unayoweza kufanya kukabiliana na maumivu:
    ● Chukua chupa ya plastiki iliyojazwa maji ya vuguvugu au kitambaa kilicholowekwa kwenye maji ya vuguvugu na kiweke chini ya mgongo au chini ya tumbo.
    ● Kunywa maji: Ni vyema kuhakikisha mwili wako unakuwa na maji ya kutosha kwa kuwa hii itakuepusha kuumwa na kichwa.
    ● Kufanya mazoezi mepesi inaweza kukusaidia kupunguza maumivu na tumbo kujaa gesi.
    ● Dawa za kupunguza maumivu kama paracetamol zinaweza kusaidia ikiwa unajisikia maumivu makali, lakini kumbuka kutumia kwa mujibu wa maelekezo ya mtaalam wa afya 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `If the pain increases, it is best to go to a health care facility for advice from a health care provider.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Maumivu yakiongeza ni vema kufika katika kituo cha kutolea huduma za afya kwa ushauri toka kwa mtoa huduma wa afya.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },

    // OVULATION_AND_FERTILITY
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Most girls experience their first menstrual period between the ages of 9 and 16 years. 
The first period is called menarche. Some girls may start earlier while others may start later. 
This is often normal because bodies develop at different rates.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasichana wengi hupata hedhi yao ya kwanza kati ya umri wa miaka 9 na 16. 
Hedhi ya kwanza inaitwa menarche. Baadhi ya wasichana wanaweza kuanza mapema huku wengine wakichelewa. 
Hii mara nyingi ni kawaida kwa sababu miili hukua kwa viwango tofauti.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `A girl can become pregnant if sperm fertilizes an egg after ovulation.
Because ovulation may occur before a menstrual period, pregnancy can happen even before a girl has had her first period.
Menstruation therefore does not protect someone from pregnancy. However, a girl can get pregnant before her first period if a mature egg is fertilized by sperm during unprotected sex. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Msichana anaweza kupata mimba ikiwa manii itarutubisha yai baada ya ovulation.
Kwa sababu ovulation inaweza kutokea kabla ya hedhi, mimba inaweza kutokea hata kabla ya msichana kupata hedhi yake ya kwanza.
Kwa hivyo, hedhi haimlindi mtu kutokana na ujauzito. Hata hivyo msichana anaweza kupata ujauzito kabla ya kupata hedhi ya kwanza ikiwa yai liliopevuka litarutubishwa na mbegu ya kiume wakati wa tendo la ngono bila kinga. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `It is best to avoid unprotected sex during puberty.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ni vizuri kujiepusha na ngono isiyo salama wakati wa balehe.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation occurs every 21 to 35 days. 
Most women have their period every 28 days. Typically, menstruation lasts 2 to 7 days. 
Some women experience abdominal pain due to uterine contractions, which occur when the uterus pushes out menstrual blood.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstrual_calendar',
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi hujirudia kila baada ya siku 21 hadi 35. 
Wanawake wengi hupata hedhi kila baada ya siku 28. Kwa kawaida, hedhi hudumu kwa siku 2 hadi 7. 
Baadhi ya wanawake hupata maumivu ya tumbo kutokana na mkakamao wa msukumo wa mji wa mimba, mkakamao huo hutokea wakati mji wa mimba unaposukuma damu ya hedhi itoke.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstrual_calendar',
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },

    // MENSTRUATION_MYTHS
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Myths and Facts about menstruation

Myth:-Menstruation is dirty blood.
Fact:-Menstrual blood is a mixture of blood and tissue from the uterus. It is a natural body process.

Myth:-Girls should not attend school during their period.
Fact:-Girls can safely continue attending school and participating in activities.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Dhana Potofu na Ukweli kuhusu hedhi

Dhana Potofu:-Hedhi ni damu chafu.
Ukweli:-Hedhi ni mchakato wa kawaida wa mwili.

Dhana Potofu:-Msichana hatakiwi kwenda shule akiwa kwenye hedhi.
Ukweli:-Msichana anaweza kuendelea na masomo na shughuli zake za kawaida.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Myth:-A girl cannot become pregnant before her first period.
Fact:-Pregnancy can occur if ovulation happens before the first menstrual period.

Myth:-Menstruation means a girl is ready for marriage.
Fact:-Menstruation is a biological process and does not mean a girl is physically, emotionally, or socially ready for marriage
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Dhana Potofu:-Msichana hawezi kupata mimba kabla ya hedhi ya kwanza.
Ukweli:-Mimba inaweza kutokea kama yai limetolewa kabla ya hedhi ya kwanza.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Common Concerns from adolescents

"My period has not started yet."
Many girls begin menstruation at different ages. If there are concerns, speaking with a healthcare provider can be helpful.

"My period is irregular."
Irregular periods are common during the first few years after menstruation begins.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasiwasi wa Kawaida kutoka kwa vijana balehe

"Hedhi yangu haijaanza bado." 
Wasichana wengi huanza hedhi katika umri tofauti. Ikiwa kuna wasiwasi, kuzungumza na mtoa huduma ya afya kunaweza kusaidia.

"Hedhi yangu si ya kawaida."
Hedhi zisizo za kawaida ni za kawaida katika miaka michache ya kwanza baada ya hedhi kuanza.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Common Concerns from adolescents

"My period is late."
Many factors such as stress, illness, nutrition, physical activity, and pregnancy can affect menstrual cycles.

"I have pain during my period."
Mild discomfort is common, but severe pain should be discussed with a healthcare provider.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasiwasi wa Kawaida kutoka kwa vijana balehe

"Hedhi yangu imechelewa." 
Mambo mengi kama vile msongo wa mawazo, ugonjwa, lishe, shughuli za kimwili, na ujauzito yanaweza kuathiri mzunguko wa hedhi.

"Nina maumivu wakati wa hedhi yangu." 
Usumbufu mdogo ni wa kawaida, lakini maumivu makali yanapaswa kujadiliwa na mtoa huduma ya afya."
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_COMMON_CONCERNS',
      nodeKey: 'MENSTRUATION_COMMON_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Common concerns content will be added here.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_COMMON_CONCERNS',
      nodeKey: 'MENSTRUATION_COMMON_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Maudhui ya wasiwasi wa kawaida yataongezwa hapa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_SUPPORT',
      nodeKey: 'MENSTRUATION_SUPPORT_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Support information for menstruation will be added here.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_SUPPORT',
      nodeKey: 'MENSTRUATION_SUPPORT_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Taarifa za msaada kuhusu hedhi zitaongezwa hapa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
  ],

  contentNodeOptions: [
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_01',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_02',
      optionValue: 'how_happens',
      labelEn: 'How does it happen?',
      labelSw: 'Hutokeaje?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_03',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_04',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_05',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_06',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_06',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_07',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_07',
      optionValue: 'important_message',
      labelEn: 'Important message',
      labelSw: 'Ujumbe muhimu',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_08',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_08',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_09',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      optionValue: 'common_questions',
      labelEn: 'Common questions',
      labelSw: 'Maswali',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'explore_hygiene',
      labelEn: 'Period hygiene',
      labelSw: 'Usafi wa hedhi',
      nextNodeKey: 'MENSTRUAL_HYGIENE_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'explore_cramps',
      labelEn: 'Period pain',
      labelSw: 'Maumivu ya hedhi',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'main_menu',
      labelEn: 'Main menu',
      labelSw: 'Menyu kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      optionValue: 'safe_cleaning',
      labelEn: 'How do I stay clean?',
      labelSw: 'Usafi unakuaje?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      optionValue: 'used_products',
      labelEn: 'Handling of pads',
      labelSw: 'Utumiaji wa pedi',
      nextNodeKey: 'MENSTRUAL_HYGIENE_03',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      optionValue: 'daily_life',
      labelEn: 'Can I stay active?',
      labelSw: 'Naweza kufanya kazi?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_04',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      optionValue: 'used_products',
      labelEn: 'Handling of pads',
      labelSw: 'Utumiaji wa pedi',
      nextNodeKey: 'MENSTRUAL_HYGIENE_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      optionValue: 'daily_life',
      labelEn: 'Can I stay active?',
      labelSw: 'Naweza kufanya kazi?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_04',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'main_menu',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      optionValue: 'daily_life',
      labelEn: 'Can I stay active?',
      labelSw: 'Naweza kufanya kazi?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      optionValue: 'safe_cleaning',
      labelEn: 'How stay clean?',
      labelSw: 'Kubaki msafi?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_02',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'main_menu',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      optionValue: 'period_pain',
      labelEn: 'Period pain',
      labelSw: 'Maumivu ya hedhi',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      optionValue: 'what_is_menstruation',
      labelEn: 'What is a period?',
      labelSw: 'Hedhi ni nini?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      optionValue: 'main_menu',
      labelEn: 'Main menu',
      labelSw: 'Menyu kuu',
      nextNodeKey: 'main_menu',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      optionValue: 'tell_me_more',
      labelEn: 'Why is it painful?',
      labelSw: 'Sababu za maumivu?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      optionValue: 'what_can_help',
      labelEn: 'What can help?',
      labelSw: 'Nini kitasaidia?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      optionValue: 'when_get_help',
      labelEn: 'When do I get help?',
      labelSw: 'Nipate msaada lini?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      optionValue: 'what_can_help',
      labelEn: 'What can help?',
      labelSw: 'Nini kitasaidia?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      optionValue: 'when_get_help',
      labelEn: 'When do I get help?',
      labelSw: 'Nipate msaada lini?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'main_menu',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      optionValue: 'when_get_help',
      labelEn: 'When do I get help?',
      labelSw: 'Nipate msaada lini?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      optionValue: 'tell_me_more',
      labelEn: 'Why is it painful?',
      labelSw: 'Sababu za maumivu?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      optionValue: 'what_can_help',
      labelEn: 'What can help?',
      labelSw: 'Nini kitasaidia?',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      optionValue: 'tell_me_about_ovulation',
      labelEn: 'Age of first period?',
      labelSw: 'Hedhi huanza lini?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      optionValue: 'tell_me_more',
      labelEn: 'Causes of pregnancy?',
      labelSw: 'Mimba hutokeaje?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      optionValue: 'cycle_timing',
      labelEn: 'Cycle timing',
      labelSw: 'Muda wa mzunguko',
      nextNodeKey: 'OVULATION_AND_FERTILITY_04',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      optionValue: 'tell_me_more',
      labelEn: 'What should I do?',
      labelSw: 'Nifanye nini?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      optionValue: 'cycle_timing',
      labelEn: 'Cycle timing',
      labelSw: 'Muda wa mzunguko',
      nextNodeKey: 'OVULATION_AND_FERTILITY_04',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      optionValue: 'cycle_timing',
      labelEn: 'Cycle timing',
      labelSw: 'Muda wa mzunguko',
      nextNodeKey: 'OVULATION_AND_FERTILITY_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      optionValue: 'back_to_pregnancy',
      labelEn: 'Causes of pregnancy?',
      labelSw: 'Mimba hutokeaje?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_02',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      optionValue: 'when_pregnancy_happens',
      labelEn: 'Causes of pregnancy?',
      labelSw: 'Mimba hutokeaje?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      optionValue: 'menstruation_myths',
      labelEn: 'Menstruation myths',
      labelSw: 'Dhana na ukweli',
      nextNodeKey: 'MENSTRUATION_MYTHS_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUATION_MYTHS_01',
      optionValue: 'tell_me_more',
      labelEn: 'More myths?',
      labelSw: 'Dhana nyingine?',
      nextNodeKey: 'MENSTRUATION_MYTHS_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_01',
      optionValue: 'common_concerns',
      labelEn: 'Common concerns',
      labelSw: 'Wasiwasi wa kawaida',
      nextNodeKey: 'MENSTRUATION_MYTHS_03',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUATION_MYTHS_02',
      optionValue: 'common_concerns',
      labelEn: 'Common concerns',
      labelSw: 'Wasiwasi wa kawaida',
      nextNodeKey: 'MENSTRUATION_MYTHS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_03',
      optionValue: 'more_concerns',
      labelEn: 'More common concerns',
      labelSw: 'Wasiwasi mwingine?',
      nextNodeKey: 'MENSTRUATION_MYTHS_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_03',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_04',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_04',
      optionValue: 'back',
      labelEn: 'Back',
      labelSw: 'Rudi',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_04',
      optionValue: 'start_again',
      labelEn: 'Start Again',
      labelSw: 'Anza Tena',
      nextNodeKey: 'START_AGAIN',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_COMMON_CONCERNS_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_SUPPORT_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 1,
      isActive: true,
    },
  ],
};
