import { InputType } from '../../../common/enums/input-type.enum';
import { Language } from '../../../common/enums/language.enum';
import { NodeType } from '../../../common/enums/node-type.enum';

export const menstruationSeed = {
  category: {
    code: 'MENSTRUATION',
    titleEn: 'Menstruation',
    titleSw: 'Hedhi',
    descriptionEn: null,
    descriptionSw: null,
    introMessageEn:
      "Let's learn about menstruation, menstrual hygiene, menstrual pain, fertility, myths and common concerns.",
    introMessageSw:
      'Karibu! Tujifunze kuhusu hedhi, usafi wa hedhi, maumivu ya hedhi, uwezo wa kushika mimba, dhana potofu na wasiwasi wa kawaida.',
    introMediaAssetKey: 'image_menstruation_intro_01',
    audienceGender: null,
    ageBandRule: null,
    sortOrder: 2,
    isActive: true,
  },

  topic: {
    code: 'MENSTRUATION',
    titleEn: 'Menstruation',
    titleSw: 'Hedhi',
    descriptionEn: null,
    descriptionSw: null,
    audienceGender: null,
    ageBandRule: null,
    sortOrder: 1,
    isActive: true,
  },

  subtopics: [
    {
      code: 'WHAT_IS_MENSTRUATION',
      titleEn: 'What is a period?',
      titleSw: 'Hedhi ni nini?',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 1,
      isActive: true,
    },
    {
      code: 'MENSTRUAL_HYGIENE',
      titleEn: 'Menstrual Hygiene',
      titleSw: 'Usafi wa Hedhi',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 2,
      isActive: true,
    },
    {
      code: 'MENSTRUAL_PAIN_AND_CONCERNS',
      titleEn: 'Pain and concerns',
      titleSw: 'Maumivu',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 3,
      isActive: true,
    },
    {
      code: 'OVULATION_AND_FERTILITY',
      titleEn: 'Ovulation',
      titleSw: 'Utoaji wa yai',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 4,
      isActive: true,
    },
    {
      code: 'MENSTRUATION_MYTHS',
      titleEn: 'Myths and facts',
      titleSw: 'Dhana na ukweli',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 5,
      isActive: true,
    },
    {
      code: 'MENSTRUATION_COMMON_CONCERNS',
      titleEn: 'Common concerns',
      titleSw: 'Wasiwasi',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 6,
      isActive: true,
    },
    {
      code: 'MENSTRUATION_SUPPORT',
      titleEn: 'Get support',
      titleSw: 'Pata msaada',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 7,
      isActive: true,
    },
  ],

  contentNodes: [
    // WHAT_IS_MENSTRUATION
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation, commonly called a period, is the monthly shedding of the lining of the uterus through the vagina when pregnancy does not occur.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_what_is_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni kumwagika kila mwezi kwa utando wa uzazi kupitia uke wakati mimba haitokei.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_what_is_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is a normal biological process and an important sign that the reproductive system is developing.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni mchakato wa kawaida wa kibiolojia na ishara muhimu kwamba mfumo wa uzazi unakua.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Each month, a girl's body prepares for a possible pregnancy.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kila mwezi, mwili wa msichana hujiandaa kwa mimba inayowezekana.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `The ovaries release an egg and the lining of the uterus becomes thicker.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ovari hutoa yai na utando wa uzazi unakuwa mzito.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_05',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `If the egg is not fertilised by sperm, pregnancy does not occur.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_05',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ikiwa yai halijarutubishwa na manii, mimba haitokei.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_06',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `The body sheds the extra uterine lining and blood through the vagina. This is called menstruation.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_06',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Mwili hutoa utando wa ziada wa uzazi na damu kupitia uke. Hii inaitwa hedhi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_07',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is a natural part of puberty and reproductive health.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_natural_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_07',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni sehemu ya asili ya kubalehe na afya ya uzazi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_natural_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_08',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is not a disease, illness, curse or punishment.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_08',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi si ugonjwa, laana wala adhabu.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Every girl experiences menstruation differently. Differences in cycle length, flow and symptoms are common.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kila msichana hupata hedhi kwa namna tofauti. Tofauti katika urefu wa mzunguko, mtiririko na dalili ni za kawaida.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.EN,
      messageText: `Choose a question.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 10,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      nodeType: NodeType.RELATED_TOPICS,
      language: Language.SW,
      messageText: `Chagua swali Tujipime...`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 10,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_11',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `How long does a period usually last?

Most periods last between 2 and 7 days.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 11,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_11',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi hudumu kwa muda gani?

Kwa kawaida hedhi hudumu kati ya siku 2 hadi 7.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 11,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_12',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Is it normal to have irregular periods?

Yes. Irregular cycles are common during adolescence.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 12,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_12',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Je, hedhi isiyo ya kawaida ni jambo la kawaida?

Ndiyo. Hasa katika miaka ya mwanzo baada ya hedhi kuanza.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 12,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_13',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Can I play sports during my period?

Yes. Physical activity is generally safe during menstruation.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 13,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_13',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Swali hili halikuwa na jibu linalolingana katika maudhui ya Kiswahili yaliyotolewa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 13,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_14',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Can stress affect my period?

Yes. Stress may affect menstrual cycles.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 14,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_14',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Swali hili halikuwa na jibu linalolingana katika maudhui ya Kiswahili yaliyotolewa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 14,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_15',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Is it normal to have cramps?

Mild cramps are common. Severe pain should be discussed with a healthcare provider.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 15,
      isActive: true,
    },
    {
      subtopicCode: 'WHAT_IS_MENSTRUATION',
      nodeKey: 'WHAT_IS_MENSTRUATION_15',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Je, maumivu wakati wa hedhi ni kawaida?

Maumivu madogo ni kawaida, lakini maumivu makali yanahitaji ushauri wa mtoa huduma ya afya.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 15,
      isActive: true,
    },

    // MENSTRUAL_HYGIENE
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstrual hygiene means practices that help girls and women manage menstruation safely, comfortably and with dignity.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_hygiene_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Usafi wa hedhi unamaanisha desturi zinazowasaidia wasichana na wanawake kusimamia hedhi yao kwa usalama, raha na kwa heshima.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_hygiene_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Good menstrual hygiene is important for health, confidence and daily wellbeing.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Usafi mzuri wa hedhi ni muhimu kwa afya, kujiamini na ustawi wa kila siku.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Use clean menstrual products such as sanitary pads, tampons, menstrual cups or clean reusable cloths that have been properly washed and dried.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Tumia bidhaa safi za hedhi kama pedi, tamponi, vikombe vya hedhi au vitambaa safi vinavyoweza kutumika tena vilivyooshwa na kukaushwa ipasavyo.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstrual products should usually be changed every 4-8 hours, depending on the flow.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_hygiene_change_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Bidhaa za hedhi zinapaswa kubadilishwa kwa kawaida kila baada ya saa 4-8, kulingana na mtiririko.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_hygiene_change_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_05',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Changing products regularly helps prevent discomfort, bad odour, skin irritation and infections.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_05',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kubadilisha bidhaa mara kwa mara husaidia kuzuia usumbufu, harufu mbaya, muwasho wa ngozi na maambukizi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_06',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Wash the genital area daily with clean water`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_06',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Osha sehemu za siri kila siku kwa maji safi`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_07',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `The vagina naturally cleans itself. There is no need to use harsh chemicals, perfumes or vaginal cleansing products.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_07',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Uke hujisafisha wenyewe kiasili. Hakuna haja ya kutumia kemikali kali, manukato au bidhaa za kusafisha uke.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_08',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Wash your hands before and after changing menstrual products to reduce the risk of infections.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_08',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Nawa mikono kabla na baada ya kubadilisha bidhaa za hedhi ili kupunguza hatari ya maambukizi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_09',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Wrap used disposable pads and place them in a bin. Do not flush them down the toilet.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_09',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Funga pedi zilizotumika na uzitupe kwenye pipa la taka. Usizitupe ndani ya choo.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_10',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Reusable materials should be washed thoroughly with clean water and soap and dried in direct sunlight whenever possible.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 10,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_10',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Vifaa vinavyoweza kutumika tena vinapaswa kuoshwa vizuri kwa maji safi na sabuni na kukaushwa kwenye jua moja kwa moja inapowezekana.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 10,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_11',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Many girls continue attending school, playing sports and participating in normal activities during menstruation.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 11,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_11',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasichana wengi huendelea kuhudhuria shule, kucheza michezo na kushiriki katika shughuli za kawaida wakati wa hedhi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 11,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_12',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Eating a balanced diet, drinking enough water and getting adequate rest can help manage menstrual discomfort.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 12,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_12',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kula lishe bora, kunywa maji ya kutosha na kupata mapumziko ya kutosha kunaweza kusaidia kudhibiti usumbufu wa hedhi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 12,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_13',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation is a normal and healthy part of growing up. Good menstrual hygiene helps girls stay healthy, comfortable and confident.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_hygiene_final_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 13,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_HYGIENE',
      nodeKey: 'MENSTRUAL_HYGIENE_13',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi ni sehemu ya kawaida na yenye afya ya kukua. Usafi mzuri wa hedhi huwasaidia wasichana kuwa na afya, starehe na kujiamini.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_hygiene_final_01',
      isStartNode: false,
      isEndNode: false,
      sortOrder: 13,
      isActive: true,
    },
    // MENSTRUAL_PAIN_AND_CONCERNS
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Some menstrual feelings and symptoms are common, especially during the first few years of menstruation.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_pain_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Baadhi ya hisia na dalili za hedhi ni za kawaida, hasa wakati wa miaka ya kwanza ya hedhi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstruation_pain_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },

    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Many girls experience mild abdominal pain, back pain, breast tenderness, bleeding changes, fatigue, headaches and swelling.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasichana wengi hupata maumivu madogo ya tumbo, maumivu ya mgongo, uchungu wa matiti, mabadiliko ya damu, uchovu, maumivu ya kichwa na uvimbe.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Some girls may feel embarrassed, scared, confused, angry or emotional.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Baadhi ya wasichana wanaweza kuhisi aibu, woga, kuchanganyikiwa, kukasirika au kuwa na hisia nyingi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Some girls experience abdominal pain because of uterine contractions. These happen when the uterus pushes menstrual blood out.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Baadhi ya wasichana hupata maumivu ya tumbo kutokana na mikakamao ya mji wa mimba wakati unasukuma damu ya hedhi itoke.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_05',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Place a plastic bottle filled with warm water or a cloth soaked in warm water under your back or lower abdomen.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_05',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Weka chupa ya plastiki yenye maji ya vuguvugu au kitambaa kilicholowekwa kwenye maji ya vuguvugu chini ya mgongo au chini ya tumbo.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_06',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Drink enough water. Keeping your body hydrated can help prevent headaches.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_06',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kunywa maji ya kutosha. Kuwa na maji ya kutosha mwilini kunaweza kusaidia kuzuia maumivu ya kichwa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_07',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Light exercise can help reduce pain and bloating or gas.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_07',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Mazoezi mepesi yanaweza kusaidia kupunguza maumivu na tumbo kujaa gesi.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_08',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Painkillers such as paracetamol may help with severe pain, but use them according to instructions from a health professional.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_08',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Dawa za kupunguza maumivu kama paracetamol zinaweza kusaidia ikiwa una maumivu makali, lakini zitumie kwa mujibu wa maelekezo ya mtaalamu wa afya.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_09',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `If the pain increases, visit a healthcare facility for advice from a healthcare provider.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUAL_PAIN_AND_CONCERNS',
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_09',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Maumivu yakiongezeka, ni vyema kufika katika kituo cha kutolea huduma za afya kwa ushauri kutoka kwa mtoa huduma wa afya.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },

    // OVULATION_AND_FERTILITY
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Most girls experience their first menstrual period between the ages of 9 and 16 years. 
The first period is called menarche. Some girls may start earlier while others may start later. 
This is often normal because bodies develop at different rates.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasichana wengi hupata hedhi yao ya kwanza kati ya umri wa miaka 9 na 16. 
Hedhi ya kwanza inaitwa menarche. Baadhi ya wasichana wanaweza kuanza mapema huku wengine wakichelewa. 
Hii mara nyingi ni kawaida kwa sababu miili hukua kwa viwango tofauti.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `A girl can become pregnant if sperm fertilizes an egg after ovulation.
Because ovulation may occur before a menstrual period, pregnancy can happen even before a girl has had her first period.
Menstruation therefore does not protect someone from pregnancy. However, a girl can get pregnant before her first period if a mature egg is fertilized by sperm during unprotected sex. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Msichana anaweza kupata mimba ikiwa manii itarutubisha yai baada ya ovulation.
Kwa sababu ovulation inaweza kutokea kabla ya hedhi, mimba inaweza kutokea hata kabla ya msichana kupata hedhi yake ya kwanza.
Kwa hivyo, hedhi haimlindi mtu kutokana na ujauzito. Hata hivyo msichana anaweza kupata ujauzito kabla ya kupata hedhi ya kwanza ikiwa yai liliopevuka litarutubishwa na mbegu ya kiume wakati wa tendo la ngono bila kinga. 
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `It is best to avoid unprotected sex during puberty.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ni vizuri kujiepusha na ngono isiyo salama wakati wa balehe.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Menstruation occurs every 21 to 35 days. 
Most women have their period every 28 days. Typically, menstruation lasts 2 to 7 days. 
Some women experience abdominal pain due to uterine contractions, which occur when the uterus pushes out menstrual blood.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstrual_calendar',
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'OVULATION_AND_FERTILITY',
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Hedhi hujirudia kila baada ya siku 21 hadi 35. 
Wanawake wengi hupata hedhi kila baada ya siku 28. Kwa kawaida, hedhi hudumu kwa siku 2 hadi 7. 
Baadhi ya wanawake hupata maumivu ya tumbo kutokana na mkakamao wa msukumo wa mji wa mimba, mkakamao huo hutokea wakati mji wa mimba unaposukuma damu ya hedhi itoke.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_menstrual_calendar',
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },

    // MENSTRUATION_MYTHS
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Myths and Facts about menstruation

Myth:-Menstruation is dirty blood.
Fact:-Menstrual blood is a mixture of blood and tissue from the uterus. It is a natural body process.

Myth:-Girls should not attend school during their period.
Fact:-Girls can safely continue attending school and participating in activities.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Dhana Potofu na Ukweli kuhusu hedhi

Dhana Potofu:-Hedhi ni damu chafu.
Ukweli:-Hedhi ni mchakato wa kawaida wa mwili.

Dhana Potofu:-Msichana hatakiwi kwenda shule akiwa kwenye hedhi.
Ukweli:-Msichana anaweza kuendelea na masomo na shughuli zake za kawaida.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Myth:-A girl cannot become pregnant before her first period.
Fact:-Pregnancy can occur if ovulation happens before the first menstrual period.

Myth:-Menstruation means a girl is ready for marriage.
Fact:-Menstruation is a biological process and does not mean a girl is physically, emotionally, or socially ready for marriage
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Dhana Potofu:-Msichana hawezi kupata mimba kabla ya hedhi ya kwanza.
Ukweli:-Mimba inaweza kutokea kama yai limetolewa kabla ya hedhi ya kwanza.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Common Concerns from adolescents

"My period has not started yet."
Many girls begin menstruation at different ages. If there are concerns, speaking with a healthcare provider can be helpful.

"My period is irregular."
Irregular periods are common during the first few years after menstruation begins.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasiwasi wa Kawaida kutoka kwa vijana balehe

"Hedhi yangu haijaanza bado." 
Wasichana wengi huanza hedhi katika umri tofauti. Ikiwa kuna wasiwasi, kuzungumza na mtoa huduma ya afya kunaweza kusaidia.

"Hedhi yangu si ya kawaida."
Hedhi zisizo za kawaida ni za kawaida katika miaka michache ya kwanza baada ya hedhi kuanza.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Common Concerns from adolescents

"My period is late."
Many factors such as stress, illness, nutrition, physical activity, and pregnancy can affect menstrual cycles.

"I have pain during my period."
Mild discomfort is common, but severe pain should be discussed with a healthcare provider.
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_MYTHS',
      nodeKey: 'MENSTRUATION_MYTHS_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wasiwasi wa Kawaida kutoka kwa vijana balehe

"Hedhi yangu imechelewa." 
Mambo mengi kama vile msongo wa mawazo, ugonjwa, lishe, shughuli za kimwili, na ujauzito yanaweza kuathiri mzunguko wa hedhi.

"Nina maumivu wakati wa hedhi yangu." 
Usumbufu mdogo ni wa kawaida, lakini maumivu makali yanapaswa kujadiliwa na mtoa huduma ya afya."
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_COMMON_CONCERNS',
      nodeKey: 'MENSTRUATION_COMMON_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Common concerns content will be added here.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_COMMON_CONCERNS',
      nodeKey: 'MENSTRUATION_COMMON_CONCERNS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Maudhui ya wasiwasi wa kawaida yataongezwa hapa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_SUPPORT',
      nodeKey: 'MENSTRUATION_SUPPORT_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Support information for menstruation will be added here.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'MENSTRUATION_SUPPORT',
      nodeKey: 'MENSTRUATION_SUPPORT_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Taarifa za msaada kuhusu hedhi zitaongezwa hapa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
  ],

  contentNodeOptions: [
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_01',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_02',
      optionValue: 'how_happens',
      labelEn: 'How does it happen?',
      labelSw: 'Hutokeaje?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_03',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_04',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_05',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_06',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_06',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_07',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_07',
      optionValue: 'important_message',
      labelEn: 'Important message',
      labelSw: 'Ujumbe muhimu',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_08',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_08',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_09',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      optionValue: 'common_questions',
      labelEn: 'Common questions',
      labelSw: 'Maswali',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_09',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'how_long',
      labelEn: 'How long?',
      labelSw: 'Muda gani?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_11',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'irregular_periods',
      labelEn: 'Irregular periods?',
      labelSw: 'Hedhi si kawaida?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_12',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'play_sports',
      labelEn: 'Play sports?',
      labelSw: 'Michezo?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_13',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'stress_effects',
      labelEn: 'Stress effects?',
      labelSw: 'Msongo?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_14',
      sortOrder: 4,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_10',
      optionValue: 'period_cramps',
      labelEn: 'Period cramps?',
      labelSw: 'Maumivu?',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_15',
      sortOrder: 5,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_11',
      optionValue: 'another_question',
      labelEn: 'Another question',
      labelSw: 'Swali jingine',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_12',
      optionValue: 'another_question',
      labelEn: 'Another question',
      labelSw: 'Swali jingine',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_13',
      optionValue: 'another_question',
      labelEn: 'Another question',
      labelSw: 'Swali jingine',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_14',
      optionValue: 'another_question',
      labelEn: 'Another question',
      labelSw: 'Swali jingine',
      nextNodeKey: 'WHAT_IS_MENSTRUATION_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_15',
      optionValue: 'pain_support',
      labelEn: 'Pain support',
      labelSw: 'Msaada maumivu',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'WHAT_IS_MENSTRUATION_15',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUAL_HYGIENE_01',
      optionValue: 'why_matters',
      labelEn: 'Why it matters',
      labelSw: 'Kwa nini muhimu?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_02',
      optionValue: 'menstrual_products',
      labelEn: 'Products',
      labelSw: 'Bidhaa za hedhi',
      nextNodeKey: 'MENSTRUAL_HYGIENE_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_03',
      optionValue: 'changing_products',
      labelEn: 'Changing products',
      labelSw: 'Badili bidhaa',
      nextNodeKey: 'MENSTRUAL_HYGIENE_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_04',
      optionValue: 'why_change',
      labelEn: 'Why change?',
      labelSw: 'Kwa nini?',
      nextNodeKey: 'MENSTRUAL_HYGIENE_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_05',
      optionValue: 'washing_safely',
      labelEn: 'Washing safely',
      labelSw: 'Kuosha salama',
      nextNodeKey: 'MENSTRUAL_HYGIENE_06',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_06',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'MENSTRUAL_HYGIENE_07',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_07',
      optionValue: 'handwashing',
      labelEn: 'Handwashing',
      labelSw: 'Kunawa mikono',
      nextNodeKey: 'MENSTRUAL_HYGIENE_08',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_08',
      optionValue: 'disposal',
      labelEn: 'Disposal',
      labelSw: 'Utupaji',
      nextNodeKey: 'MENSTRUAL_HYGIENE_09',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_09',
      optionValue: 'reusable_materials',
      labelEn: 'Reusable materials',
      labelSw: 'Vifaa vya kurudia',
      nextNodeKey: 'MENSTRUAL_HYGIENE_10',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_10',
      optionValue: 'daily_activities',
      labelEn: 'Daily activities',
      labelSw: 'Shughuli kawaida',
      nextNodeKey: 'MENSTRUAL_HYGIENE_11',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_11',
      optionValue: 'wellbeing_tips',
      labelEn: 'Wellbeing tips',
      labelSw: 'Vidokezo',
      nextNodeKey: 'MENSTRUAL_HYGIENE_12',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_12',
      optionValue: 'final_message',
      labelEn: 'Final message',
      labelSw: 'Ujumbe wa mwisho',
      nextNodeKey: 'MENSTRUAL_HYGIENE_13',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_13',
      optionValue: 'period_pain',
      labelEn: 'Pain and concerns',
      labelSw: 'Maumivu',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_13',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_HYGIENE_13',
      optionValue: 'get_support',
      labelEn: 'Get support',
      labelSw: 'Pata msaada',
      nextNodeKey: 'MENSTRUATION_SUPPORT_01',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_01',
      optionValue: 'common_symptoms',
      labelEn: 'Common symptoms',
      labelSw: 'Dalili za kawaida',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_02',
      optionValue: 'emotional_feelings',
      labelEn: 'Emotional feelings',
      labelSw: 'Hisia',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_03',
      optionValue: 'why_cramps_happen',
      labelEn: 'Why cramps happen',
      labelSw: 'Chanzo maumivu',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_04',
      optionValue: 'pain_relief_tips',
      labelEn: 'Pain relief tips',
      labelSw: 'Punguza maumivu',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_05',
      optionValue: 'another_tip',
      labelEn: 'Another tip',
      labelSw: 'Kidokezo kingine',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_06',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_06',
      optionValue: 'another_tip',
      labelEn: 'Another tip',
      labelSw: 'Kidokezo kingine',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_07',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_07',
      optionValue: 'pain_medicine',
      labelEn: 'Pain medicine',
      labelSw: 'Dawa ya maumivu',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_08',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_08',
      optionValue: 'when_seek_help',
      labelEn: 'When to seek help',
      labelSw: 'Wakati wa msaada',
      nextNodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_09',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_09',
      optionValue: 'get_support',
      labelEn: 'Get support',
      labelSw: 'Pata msaada',
      nextNodeKey: 'MENSTRUATION_SUPPORT_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUAL_PAIN_AND_CONCERNS_09',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },

    {
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      optionValue: 'tell_me_more',
      labelEn: 'Causes of pregnancy?',
      labelSw: 'Mimba hutokeaje?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      optionValue: 'cycle_timing',
      labelEn: 'Cycle timing',
      labelSw: 'Muda wa mzunguko',
      nextNodeKey: 'OVULATION_AND_FERTILITY_04',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      optionValue: 'tell_me_more',
      labelEn: 'What should I do?',
      labelSw: 'Nifanye nini?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      optionValue: 'cycle_timing',
      labelEn: 'Cycle timing',
      labelSw: 'Muda wa mzunguko',
      nextNodeKey: 'OVULATION_AND_FERTILITY_04',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      optionValue: 'cycle_timing',
      labelEn: 'Cycle timing',
      labelSw: 'Muda wa mzunguko',
      nextNodeKey: 'OVULATION_AND_FERTILITY_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      optionValue: 'back_to_pregnancy',
      labelEn: 'Causes of pregnancy?',
      labelSw: 'Mimba hutokeaje?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_02',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_03',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      optionValue: 'when_pregnancy_happens',
      labelEn: 'Causes of pregnancy?',
      labelSw: 'Mimba hutokeaje?',
      nextNodeKey: 'OVULATION_AND_FERTILITY_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      optionValue: 'menstruation_myths',
      labelEn: 'Menstruation myths',
      labelSw: 'Dhana na ukweli',
      nextNodeKey: 'MENSTRUATION_MYTHS_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'OVULATION_AND_FERTILITY_04',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUATION_MYTHS_01',
      optionValue: 'tell_me_more',
      labelEn: 'More myths?',
      labelSw: 'Dhana nyingine?',
      nextNodeKey: 'MENSTRUATION_MYTHS_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_01',
      optionValue: 'common_concerns',
      labelEn: 'Common concerns',
      labelSw: 'Wasiwasi wa kawaida',
      nextNodeKey: 'MENSTRUATION_MYTHS_03',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'MENSTRUATION_MYTHS_02',
      optionValue: 'common_concerns',
      labelEn: 'Common concerns',
      labelSw: 'Wasiwasi wa kawaida',
      nextNodeKey: 'MENSTRUATION_MYTHS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_03',
      optionValue: 'more_concerns',
      labelEn: 'More common concerns',
      labelSw: 'Wasiwasi mwingine?',
      nextNodeKey: 'MENSTRUATION_MYTHS_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_03',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_04',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_04',
      optionValue: 'back',
      labelEn: 'Back',
      labelSw: 'Rudi',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_MYTHS_04',
      optionValue: 'start_again',
      labelEn: 'Start Again',
      labelSw: 'Anza Tena',
      nextNodeKey: 'START_AGAIN',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_COMMON_CONCERNS_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'MENSTRUATION_SUPPORT_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 1,
      isActive: true,
    },
  ],
};


