import { InputType } from '../../../common/enums/input-type.enum';
import { Language } from '../../../common/enums/language.enum';
import { NodeType } from '../../../common/enums/node-type.enum';

export const pubertyAdolescentDevelopmentSeed = {
  category: {
    code: 'PUBERTY_ADOLESCENT_DEVELOPMENT',
    titleEn: 'Puberty',
    titleSw: 'Balehe',
    descriptionEn: null,
    descriptionSw: null,
    introMessageEn:
      "Let's talk about puberty and adolescent development. Puberty includes normal physical and emotional changes. These changes happen at different times for different young people.",
    introMessageSw:
      'Karibu! Tuzungumze kuhusu balehe na ukuaji wa vijana. Balehe huhusisha mabadiliko ya kawaida ya kimwili na kihisia. Mabadiliko haya hutokea kwa nyakati tofauti kwa vijana tofauti.',
    introMediaAssetKey: 'image_puberty_changes_01',
    audienceGender: null,
    ageBandRule: null,
    sortOrder: 1,
    isActive: true,
  },

  topic: {
    code: 'PUBERTY_ADOLESCENT_DEVELOPMENT',
    titleEn: 'Puberty',
    titleSw: 'Balehe',
    descriptionEn: null,
    descriptionSw: null,
    audienceGender: null,
    ageBandRule: null,
    sortOrder: 1,
    isActive: true,
  },

  subtopics: [
    {
      code: 'BODY_CHANGES',
      titleEn: 'Body Changes',
      titleSw: 'Mabadiliko ya Mwili',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 1,
      isActive: true,
    },
    {
      code: 'UNDERSTANDING_PUBERTY',
      titleEn: 'Understanding Puberty',
      titleSw: 'Kuelewa balehe',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 2,
      isActive: true,
    },
    {
      code: 'PHYSICAL_CHANGES_IN_GIRLS',
      titleEn: 'Changes in Girls',
      titleSw: 'Mabadiliko kwa Wasichana',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 3,
      isActive: true,
    },
    {
      code: 'PHYSICAL_CHANGES_IN_BOYS',
      titleEn: 'Changes in Boys',
      titleSw: 'Mabadiliko kwa Wavulana',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 4,
      isActive: true,
    },
    {
      code: 'EMOTIONAL_CHANGES_DURING_PUBERTY',
      titleEn: 'Emotional Changes',
      titleSw: 'Mabadiliko ya Hisia',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 5,
      isActive: true,
    },
    {
      code: 'PUBERTY_SUPPORT',
      titleEn: 'Get Support',
      titleSw: 'Pata msaada',
      descriptionEn: null,
      descriptionSw: null,
      audienceGender: null,
      ageBandRule: null,
      sortOrder: 6,
      isActive: true,
    },
  ],

  contentNodes: [
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'BODY_CHANGES_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `During puberty, the body goes through normal physical and emotional changes. These changes can happen at different times for different young people.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_puberty_changes_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'BODY_CHANGES_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wakati wa balehe, mwili hupitia mabadiliko ya kawaida ya kimwili na kihisia. Mabadiliko haya yanaweza kutokea kwa nyakati tofauti kwa vijana tofauti.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: 'image_puberty_changes_01',
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'BODY_CHANGES_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `During puberty, adolescents learn about personal hygiene, body image and self-esteem.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'BODY_CHANGES_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wakati wa kubalehe, vijana hujifunza kuhusu usafi wa mwili, taswira ya mwili na kujithamini.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'BODY_CHANGES_QUIZ_PLACEHOLDER_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Body changes quiz will be added here.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'BODY_CHANGES_QUIZ_PLACEHOLDER_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Jaribio la mabadiliko ya mwili litaongezwa hapa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 3,
      isActive: true,
    },

    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Puberty is the stage of life when a child's body begins to develop into an adult body capable of reproduction. It is a normal and natural part of growing up.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Balehe ni kipindi cha ukuaji ambapo mwili wa mtoto huanza kubadilika na kuwa mwili wa mtu mzima mwenye uwezo wa kuzaa. Balehe ni sehemu ya kawaida ya maisha.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Puberty happens to everyone, although the timing and pace may differ from one person to another.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Balehe hutokea kwa kila mtu, ingawa muda na kasi ya mabadiliko hutofautiana.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Puberty usually begins between ages 8-13 for girls and 9-14 for boys. Some young people may begin earlier or later. These differences are usually normal.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kwa kawaida wasichana huanza balehe kati ya miaka 8 hadi 13 na wavulana kati ya miaka 9 hadi 14, ingawa wengine wanaweza kuanza mapema au kuchelewa kidogo.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_04',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `During puberty, the body produces hormones that trigger physical, emotional and social changes. Hormones are natural chemical messengers produced by glands in the body.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_04',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wakati wa balehe, mwili huzalisha homoni ambazo husababisha mabadiliko ya kimwili, kihisia na kijamii.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_05',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Sema Nami! Which statement sounds like something you have wondered about?`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_05',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Sema Nami! Ni jambo gani ambalo umewahi kujiuliza?`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_06',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `"I started puberty earlier than my friends." This is usually normal. Bodies develop at different rates.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_06',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `"Nimeingia balehe mapema kabla ya rafiki zangu." Kila mtu hupitia balehe kwa namna yake.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 6,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_07',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `"My voice is changing." Voice changes are a normal part of puberty, especially for boys.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_07',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `"Sauti yangu inabadilika." Mabadiliko ya sauti ni sehemu ya kawaida ya balehe, hususan kwa wavulana.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 7,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_08',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `"I feel emotional all the time." Hormonal changes can affect emotions during puberty. Puberty is not an illness.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_08',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `"Ninahisi hisia kila wakati." Mabadiliko ya homoni yanaweza kuathiri hisia wakati wa kubalehe. Balehe si ugonjwa.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 8,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_09',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `"My body looks different from others." Everyone develops at their own pace. Body and emotional changes are part of growing up.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },
    {
      subtopicCode: 'UNDERSTANDING_PUBERTY',
      nodeKey: 'UNDERSTANDING_PUBERTY_09',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `"Mwili wangu umekuwa tofauti ukilinganisha na wenzangu." Mabadiliko ya mwili na hisia ni sehemu ya ukuaji.`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 9,
      isActive: true,
    },

    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_GIRLS',
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `During puberty, girls may experience these physical changes:`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_GIRLS',
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wakati wa balehe, wasichana wanaweza kupitia mabadiliko haya ya mwili:`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_GIRLS',
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `1. Breast development
2. Growth of pubic and underarm hair
3. Beginning of menstruation
4. Increased height and weight`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_GIRLS',
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `1. Matiti kuanza kukua
5. Kuota nywele sehemu za siri na kwapani
6. Kuanza kupata hedhi
4. Kuongezeka kwa urefu na uzito`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_GIRLS',
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `5. Changes in body shape, such as wider hips
6. Increased sweating and body odour
7. Acne or pimples`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_GIRLS',
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `5. Nyonga kupanuka
8. Kuongezeka kwa jasho na harufu ya mwili
7. Chunusi`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'PUBERTY_LEARNING_POINTS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Understanding puberty helps young people to:

1. Build self-confidence
2. Understand body changes
3. Practise good hygiene
4. Make informed health decisions
5. Seek help when needed`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      subtopicCode: 'BODY_CHANGES',
      nodeKey: 'PUBERTY_LEARNING_POINTS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Kuelewa balehe huwasaidia vijana:

1. Kujenga kujiamini
2. Kuelewa mabadiliko ya mwili
3. Kuzingatia usafi mzuri
4. Kufanya maamuzi sahihi ya kiafya
5. Kutafuta msaada unapohitajika`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 4,
      isActive: true,
    },

    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_BOYS',
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `During puberty, boys may experience these physical changes:`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_BOYS',
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Wakati wa balehe, wavulana wanaweza kupitia mabadiliko haya ya mwili:`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_BOYS',
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `1. Enlargement of the penis and testicles
2. Growth of pubic, underarm and facial hair
3. Deepening of the voice
4. Increased muscle development`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_BOYS',
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `1. Uume na korodani kukua
5. Kuota nywele sehemu za siri, kwapani na usoni
6. Sauti kuwa nzito
4. Misuli kuongezeka`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: false,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_BOYS',
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_03',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `5. Growth spurts in height
6. Increased sweating and body odour
7. Acne or pimples
8. Wet dreams or nocturnal emissions`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 3,
      isActive: true,
    },
    {
      subtopicCode: 'PHYSICAL_CHANGES_IN_BOYS',
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_03',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `5. Kuongezeka kwa urefu
9. Jasho na harufu ya mwili kuongezeka
10. Chunusi
8. Ndoto za usiku`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 3,
      isActive: true,
    },

    {
      subtopicCode: 'EMOTIONAL_CHANGES_DURING_PUBERTY',
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Many young people experience emotional changes during puberty because of hormonal changes and new social experiences. These may include

    • Mood swings
    • Increased sensitivity
    • Desire for independence
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'EMOTIONAL_CHANGES_DURING_PUBERTY',
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Mabadiliko ya Kihisia

    • Kubadilika kwa hisia mara kwa mara
    • Kuwa na hisia kali zaidi
    • Kutaka kujitegemea
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: false,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'EMOTIONAL_CHANGES_DURING_PUBERTY',
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_02',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `Some more emotional changes may include:

    • Strong emotions
    • Attraction to other people
    • Concern about appearance
    • Curiosity about relationships
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'EMOTIONAL_CHANGES_DURING_PUBERTY',
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_02',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Mabadiliko ya Kihisia

    • Kuvutiwa na watu wengine
    • Kujali zaidi mwonekano wa mwili
    • Kutaka kueleweka na kukubalika
`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: false,
      isEndNode: true,
      sortOrder: 2,
      isActive: true,
    },
    {
      subtopicCode: 'PUBERTY_SUPPORT',
      nodeKey: 'PUBERTY_SUPPORT_01',
      nodeType: NodeType.CONTENT,
      language: Language.EN,
      messageText: `If you need health information, support, or guidance about puberty, you do not have to face it alone. You can speak to a trusted parent, guardian, teacher, counselor, healthcare provider, or a youth-friendly health service.

For additional support, guidance, or referrals, you can contact OVAH through:
Phone/WhatsApp: 0652 522 358`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      subtopicCode: 'PUBERTY_SUPPORT',
      nodeKey: 'PUBERTY_SUPPORT_01',
      nodeType: NodeType.CONTENT,
      language: Language.SW,
      messageText: `Ikiwa unahitaji taarifa za afya, msaada, au mwongozo kuhusu balehe, usibaki peke yako. Unaweza kuzungumza na mzazi, mlezi, mwalimu, mshauri, mtoa huduma za afya, au huduma rafiki kwa vijana.

Kwa msaada zaidi, ushauri au maelekezo ya huduma zinazopatikana, unaweza kuwasiliana na OVAH kupitia:
Simu/WhatsApp: 0652 522 358`,
      inputType: InputType.BUTTON,
      mediaAssetKey: null,
      isStartNode: true,
      isEndNode: true,
      sortOrder: 1,
      isActive: true,
    },
  ],

  contentNodeOptions: [
    {
      nodeKey: 'BODY_CHANGES_01',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'BODY_CHANGES_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'BODY_CHANGES_02',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'BODY_CHANGES_02',
      optionValue: 'i_need_support',
      labelEn: 'I need support',
      labelSw: 'Nahitaji msaada',
      nextNodeKey: 'PUBERTY_SUPPORT_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'BODY_CHANGES_02',
      optionValue: 'take_quiz',
      labelEn: 'Take quiz',
      labelSw: 'Fanya jaribio',
      nextNodeKey: 'BODY_CHANGES_QUIZ_PLACEHOLDER_01',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'BODY_CHANGES_QUIZ_PLACEHOLDER_01',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PUBERTY_SUPPORT_01',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 1,
      isActive: true,
    },

    {
      nodeKey: 'UNDERSTANDING_PUBERTY_01',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_02',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_03',
      optionValue: 'continue',
      labelEn: 'Continue',
      labelSw: 'Endelea',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_04',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_04',
      optionValue: 'common_concerns',
      labelEn: 'Common concerns',
      labelSw: 'Wasiwasi kawaida',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_04',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_05',
      optionValue: 'started_early',
      labelEn: 'Started early',
      labelSw: 'Nimeanza mapema',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_06',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_05',
      optionValue: 'voice_changing',
      labelEn: 'Voice changing',
      labelSw: 'Sauti inabadilika',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_07',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_05',
      optionValue: 'strong_emotions',
      labelEn: 'Strong emotions',
      labelSw: 'Hisia nyingi',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_08',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_05',
      optionValue: 'body_different',
      labelEn: 'Body looks different',
      labelSw: 'Mwili tofauti',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_09',
      sortOrder: 4,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_06',
      optionValue: 'another_concern',
      labelEn: 'Another concern',
      labelSw: 'Jambo jingine',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_06',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_07',
      optionValue: 'another_concern',
      labelEn: 'Another concern',
      labelSw: 'Jambo jingine',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_07',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_08',
      optionValue: 'another_concern',
      labelEn: 'Another concern',
      labelSw: 'Jambo jingine',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_08',
      optionValue: 'emotional_changes',
      labelEn: 'Emotional changes',
      labelSw: 'Mabadiliko hisia',
      nextNodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_09',
      optionValue: 'another_concern',
      labelEn: 'Another concern',
      labelSw: 'Jambo jingine',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'UNDERSTANDING_PUBERTY_09',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },

    {
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_01',
      optionValue: 'see_changes',
      labelEn: 'See changes',
      labelSw: 'Ona mabadiliko',
      nextNodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_02',
      optionValue: 'more_changes',
      labelEn: 'More changes',
      labelSw: 'Zaidi',
      nextNodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_03',
      optionValue: 'learning_points',
      labelEn: 'Learning points',
      labelSw: 'Mambo ya kujifunza',
      nextNodeKey: 'PUBERTY_LEARNING_POINTS_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_03',
      optionValue: 'i_need_support',
      labelEn: 'I need support',
      labelSw: 'Nahitaji msaada',
      nextNodeKey: 'PUBERTY_SUPPORT_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_03',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'PUBERTY_LEARNING_POINTS_01',
      optionValue: 'take_quiz',
      labelEn: 'Take quiz',
      labelSw: 'Fanya jaribio',
      nextNodeKey: 'BODY_CHANGES_QUIZ_PLACEHOLDER_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PUBERTY_LEARNING_POINTS_01',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'PUBERTY_LEARNING_POINTS_01',
      optionValue: 'get_support',
      labelEn: 'Get support',
      labelSw: 'Pata msaada',
      nextNodeKey: 'PUBERTY_SUPPORT_01',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_01',
      optionValue: 'see_changes',
      labelEn: 'See changes',
      labelSw: 'Ona mabadiliko',
      nextNodeKey: 'PHYSICAL_CHANGES_IN_BOYS_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_02',
      optionValue: 'more_changes',
      labelEn: 'More changes',
      labelSw: 'Zaidi',
      nextNodeKey: 'PHYSICAL_CHANGES_IN_BOYS_03',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_03',
      optionValue: 'learning_points',
      labelEn: 'Learning points',
      labelSw: 'Mambo ya kujifunza',
      nextNodeKey: 'PUBERTY_LEARNING_POINTS_01',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_03',
      optionValue: 'i_need_support',
      labelEn: 'I need support',
      labelSw: 'Nahitaji msaada',
      nextNodeKey: 'PUBERTY_SUPPORT_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'PHYSICAL_CHANGES_IN_BOYS_03',
      optionValue: 'back',
      labelEn: 'Choose topic',
      labelSw: 'Chagua mada',
      nextNodeKey: 'BACK_ACTION',
      sortOrder: 3,
      isActive: true,
    },

    {
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_01',
      optionValue: 'more_emotions',
      labelEn: 'More feelings',
      labelSw: 'Mabadiliko mengine?',
      nextNodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_02',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_01',
      optionValue: 'common_worries',
      labelEn: 'Common worries',
      labelSw: 'Wasiwasi wa kawaida',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_01',
      optionValue: 'girls_changes',
      labelEn: 'Changes in Girls',
      labelSw: 'Balehe kwa Wasichana',
      nextNodeKey: 'PHYSICAL_CHANGES_IN_GIRLS_01',
      sortOrder: 3,
      isActive: true,
    },
    {
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_02',
      optionValue: 'common_worries',
      labelEn: 'Common worries',
      labelSw: 'Wasiwasi wa kawaida',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_05',
      sortOrder: 1,
      isActive: true,
    },
    {
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_02',
      optionValue: 'what_is_puberty',
      labelEn: 'What is puberty?',
      labelSw: 'Balehe ni nini?',
      nextNodeKey: 'UNDERSTANDING_PUBERTY_01',
      sortOrder: 2,
      isActive: true,
    },
    {
      nodeKey: 'EMOTIONAL_CHANGES_DURING_PUBERTY_02',
      optionValue: 'main_menu',
      labelEn: 'Main Menu',
      labelSw: 'Menyu Kuu',
      nextNodeKey: 'CATEGORY_MENU',
      sortOrder: 3,
      isActive: true,
    },
  ],
};
